apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  namespace: weather-data-collector
type: Opaque
data: 
  # base64 encoded values for MongoDB username and password
  MONGO_USERNAME: mongo-user
  MONGO_PASSWORD: momgo-pass