apiVersion: v1
kind: Secret
metadata: 
  name: weather-secrets
  namespace: weather-data-collector 
type: Opaque
stringData:
  XWEATHER_BASE_URL: "https://data.api.xweather.com/conditions/new%20york%2C%20ny?"
  XWEATHER_CLIENT_ID: "..."
  XWEATHER_CLIENT_SECRET: "...."
  XWEATHER_API_KEY: ".."