apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-local-storage
  hostPath:
    path: /mnt/data/weather-data-collector/mongo-db # Specify a path in the host for storage



